const projectsArray = [
  {
    id: 0,
    title: "Business Card",
    image: "../assets/businesscard.jpeg",
    languages: ["HTML", "CSS"],
    date: "December 27, 2023",
    link: "https://itab-card.netlify.app/",
    githubRepository: "https://github.com/Itabghazouani/Business-Card",
    description: "The Simplest Business Card as my first Project in Scrimba",
  },
  {
    id: 1,
    title: "Visit Toulouse",
    image: "../assets/toulouse.jpeg",
    languages: ["HTML", "CSS"],
    date: "January 12, 2024",
    link: "https://visit-tlse-with-itab.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Visit-toulouse",
    description: "You've never been to Toulouse. how do I know? Because you don't live there. Go, enjoy an fall in love for this beautiful city.",
  },
  {
    id: 2,
    title: "Birthday Card",
    image: "../assets/birthday.jpeg",
    languages: ["HTML", "CSS"],
    date: "December 27, 2023",
    link: "https://justine-birthday.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Birthday-Card",
    description: "Continuing my journey at Scrimba, and my girlfriend's birthday coming soon, I've realized a funny birthday card to combine business with pleasure",
  },
  {
    id: 3,
    title: "Coworking Space Site",
    image: "../assets/coworking.jpeg",
    languages: ["HTML", "CSS"],
    date: "January 16, 2024",
    link: "https://mycoworking-space-site.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Coworking-Space-Site",
    description: "This project looks simple but it was one of the most useful because it helped us understand a lot of CSS concept which for me represent the most complcated part of a frontend developer.",
  },
  {
    id: 4,
    title: "Password Generator",
    image: "../assets/password.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 5, 2024",
    link: "https://newgenerator-pw.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Password-genrerator",
    description: "Introducing the Javascript part in my Scrimba Journey, our first challenge was to generate randoms password to defend ourselves against hackers.",
  },
  {
    id: 5,
    title: "Rugby BoxScore",
    image: "../assets/boxscore.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 5, 2024",
    link: "https://rugby-boxscore.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Rugby-boxscore",
    description: "With the concept of incrementation, I've created a boxscore of this classic of game of rugby. No need to say that France would win no matter what.",
  },
  {
    id: 6,
    title: "Unit Converter",
    image: "../assets/converter.png",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 5, 2024",
    link: "https://conversion-of-unit.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Unit-converter",
    description: "as you may know, in the world, we all have our units to quantify. Here is a converter that would help you when you'd need it.",
  },
  {
    id: 7,
    title: "Shopping List App",
    image: "../assets/shopping.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 9, 2024",
    link: "https://at-least-i-have-my-list.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Shopping-List-App",
    description: "So far in my journey, it has been my most complete project. Using the firebase database, now I can have my shopping list everytime with me.",
  },
  {
    id: 8,
    title: "We Are One",
    image: "../assets/one.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 11, 2024",
    link: "https://we-are-one-sales-team.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/We-are-One",
    description: "Our salesteam have worked pretty well this year, with we are one, lets greet each other, and motivate us even more, because limit is a useless concept.",
  },
  {
    id: 9,
    title: "Oldagram",
    image: "../assets/oldagram.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 16, 2024",
    link: "https://my-goldagram.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Oldagram",
    description: "In our Scrimba Journey, we've created a copy of Instagram. it was a funny concept that allow us to use several concepts we've seen.",
  },

  {
    id: 10,
    title: "Twimba",
    image: "../assets/twimba.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 24, 2024",
    link: "https://my-twimba.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Twimba",
    description: "After our copy of Instagram, we've also created a copy of Twitter, adding new concepts to our code, like the data-attribute",
  },
  {
    id: 11,
    title: "Property Real Estate",
    image: "../assets/estate.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "January 29, 2024",
    link: "https://property-real-estate.netlify.app",
    githubRepository: "https://github.com/Itabghazouani/Property-Real-Estate",
    description: "this project allowed us to have a javascript file more concise and responsive. new concepts are used and help us going to our next project.",
  },
  {
    id: 12,
    title: "Restaurant Ordering App",
    image: "../assets/restaurant.jpeg",
    languages: ["HTML", "CSS", "Javascript"],
    date: "February 13, 2024",
    link: "https://restaurant-order-thegoat-burger.netlify.app/",
    githubRepository: "https://github.com/Itabghazouani/Restaurant-Ordering-App",
    description: "This project is the most complete we've done so far. An app to order food with almost all the concepts we've seen in our journey. It doesn't help to eat healthy, but after all, we only have one life",
  },
  {
    id: 13,
    title: "Strings and Things",
    image: "../assets/string.jpeg",
    languages: ["HTML", "SCSS", "Ruby On Rails", "Javascript"],
    date: "June 6, 2022",
    link: "https://airbnb-stephenmcg123.herokuapp.com/",
    githubRepository: "https://github.com/Stephenmcg123/Strings_and_Things",
    description: "We've all wanted at some point to play a racket sport with some friends. But we don't have the racket or we don't want to buy one. Strings and Things is the solution and offer you the opportunity to rent the racket from someone who does. We never use them too often, so being able to rent it, is a win win, for the renter or the owner."
  },
  {
    id: 14,
    title: "Snap and Eat",
    image: "../assets/snap.jpeg",
    languages: ["HTML", "SCSS", "Ruby On Rails", "Javascript"],
    date: "September 29, 2022",
    link: "https://snap-and-eat.herokuapp.com/",
    githubRepository: "https://github.com/Itabghazouani/snap_and_eat",
    description: "With my colleagues, we've created a Mobile App for people who knows what they want to eat, and able them tho find all the restaurant offering this dish. A great app for people who knows what they want."
  }
]

export default projectsArray
